### ISSUE TITLE
Add support for message header

### ISSUE THREAD

**Issue by kotnik** [jez500/bender#2]
In Homer we can have a header message before all the services, something like this:

```yaml
message:
  url: "http://192.168.88.50:8099/endpoint/"
  style: "is-danger"
  title: "Service status"
  content: "Waiting for results from statping..."
```

This is very useful to integrate various services on the dashboard, my example is to show the uptime status of all the services in the dashboard.

It is the only Homer-like feature that bender is missing, and I hope you would consider adding it.
